---
abstract: 'wrap subs with pre- and post-call hooks'
author:
  - 'John D Porter <jdporter@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Hook-WrapSub
requires:
  Exporter: '0'
  Symbol: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilbowers/Hook-WrapSub
  repository: https://github.com/neilbowers/Hook-WrapSub.git
version: '0.04'
